# Basbild
# Kör portainer.py för att distribuera/avsluta stackar i en Portainer-miljö
FROM python:3.13-alpine

# Ställ in katalog och kopiera filer
WORKDIR /app
COPY requirements-api-handler.txt requirements.txt
RUN pip install -r requirements.txt
COPY portainer.py .
