# Bas MSSQL-bild
FROM mcr.microsoft.com/mssql/server:2022-latest

# Ställ in katalog och kopiera filer dit
WORKDIR /usr/src/app
COPY databas-entry.sh .
COPY db-init.sql .

# Kör entrypoint-script för att starta mssql och sedan köra init-script för inställningar
CMD ["/bin/bash", "./databas-entry.sh"]
